# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic Publish'

# Event for the workflow
on:
  push:
    # 👇 Run the workflow on push to all branches
  pull_request:
    branches:
      - '**'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: npm install
        # 👇 Adds Chromatic as a step in the workflow
        # run only if there is affected changes
      - name: Publish to Chromatic
        if: github.event_name == 'pull_request'
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # 👇 Only run if there are changes to the components
          onlyChanged: true
