# .github/workflows/test.yml

# Workflow name
name: 'Test & Build'

# Event for the workflow
on:
  # 👇 Run the workflow on all pull request events
  pull_request:
    branches:
      - '**'

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: npm install
      - name: Run tests
        # 👇 Run tests for the affected projects
        run: npx nx affected --target=test --base=origin/main --head=HEAD --parallel --maxParallel=2 -- --passWithNoTests
      - name: Build
        # 👇 Build the project with the same build tool used in the project (replace it as needed), e.g. webpack, rollup, parcel
        run: npx nx affected --target=build --base=origin/main --head=HEAD --parallel --maxParallel=2
